.\" ***********************************************************************
.\" *  Copyright (C) 2004-2005 Remi Denis-Courmont.                       *
.\" *  This program is free software; you can redistribute and/or modify  *
.\" *  it under the terms of the GNU General Public License as published  *
.\" *  by the Free Software Foundation; version 2 of the license.         *
.\" *                                                                     *
.\" *  This program is distributed in the hope that it will be useful,    *
.\" *  but WITHOUT ANY WARRANTY; without even the implied warranty of     *
.\" *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               *
.\" *  See the GNU General Public License for more details.               *
.\" *                                                                     *
.\" *  You should have received a copy of the GNU General Public License  *
.\" *  along with this program; if not, you can get it from:              *
.\" *  http://www.gnu.org/copyleft/gpl.html                               *
.\" ***********************************************************************
.TH "MIREDO" "5" "$Date$" "miredo" "System Manager's Manual"
.SH NAME
miredo.conf \- configuration for Miredo
.SH SYNOPSIS
.B miredo.conf

.SH DESCRIPTON
.BR "miredo.conf" " is the configuration file for " "Miredo" "."
Each configuration directive consists of one directive name possibly
followed by one or several spaces and a value for the directive.
White spaces, empty lines and lines starting with '#' are ignored.

.SH GENERAL OPTIONS

.TP
.BR "\-b ip_address" " or " "\-\-bind ip_address"
Bind the Teredo relay or Teredo client to a specific IPv4 address.
By default, it is not bound to any particular IPv4 address.

Only use this option if you have trouble with the default value, such
as if you have a multi-homed host with equal-cost IPv4 routing, or if
you have specific firewalling constraints.

.TP
.BR "\-C" " or " "\-\-cone"
.RI "Assume that we are behind a " "cone" " NAT device, or no NAT at"
all (ie. that we have a public IPv4 address). This is an optimization
to emit fewer Teredo packets.
That option must not be used when Miredo serves as a Teredo client.

.TP
.BR "\-i ifname" ", " "\-\-iface ifname"
Specify the name of the Teredo tunneling interface which Miredo will
create ("teredo" by default). On some systems, it is not possible to
redefine the tunnel name.

.TP
.BR "\-p port" " or " "\-\-port port"
Define the UDP (over IPv4) port number to be used by the relay or
client (automatic by default).

.TP
.BR "\-P prefix" " or " "\-\-prefix prefix"
Override the Teredo prefix (3ffe:831f:: at the moment).
.BR "Do not use that feature" " if you don't know what you are doing, "
as it is more than likely to break your IPv6 connectivity.
That option must not be used when Miredo serves as a Teredo client.

.TP
.BR "\-s server_ip" " or " "\-\-server server_ip"
.RI "Turn on " "Teredo server mode" "."
With this option, Miredo will behave as a Teredo server on IPv4, with
.RB "primary IPv4 address " "server_ip" " and secondary IPv4 address"
.RB "server_ip + 1" "."
That option must not be used when Miredo serves as a Teredo client.

.TP
.BR "server name"
Server name should be valid a IPv4 host name or IPv4 address. Miredo
will try to qualify as a Teredo client with this Teredo server.
This enable Miredo to serve as a Teredo client.
.RB "It conflicts with options " "-C" "," "-P" " and " "-s" "."

.SH "SEE ALSO"
miredo(8)

.SH AUTHOR
Remi Denis-Courmont <rdenis at simphalempin.com>

$Id$

http://www.simphalempin.com/dev/miredo/

